name: 🔗 提交时检查 Markdown 空格
on: [pull_request_target]

jobs:
  build:
    name: AutoCorrect
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout from repository
          uses: actions/checkout@v4
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
          
        - name: Install autocorrect 
          run: uname -r && yarn add autocorrect-node && yarn autocorrect -V
        
        - name: Run autocorrect lint
          run: yarn autocorrect --config .autocorrectrc --lint --no-diff-bg-color $(git diff --diff-filter=AM --name-only ${{ github.event.pull_request.base.sha }})
 
        - name: Report ReviewDog
          if: failure()
          uses: huacnlee/autocorrect-action@main
          env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            reviewdog: true
