name: 🔗 md-padding 自动加空格

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    name: md-padding
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout from repository
          uses: actions/checkout@v4
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
          
        - name: Install Node.js dependencies and PV
          run: npm i -g md-padding && sudo apt update -y && sudo apt install pv -y
        
        - name: Run md-padding lint
          run: find "$(pwd)" -type f -name "*.md" -print0 | pv -l -0 | xargs -P 4 -I {} npx mdp -i {}

        - name: Markdown add spaces
          uses: peter-evans/create-pull-request@v6
          with:
             commit-message: "Markdown add spaces"
             labels: "Markdown"
             delete-branch: true
             title: Markdown add spaces
             body: 格式化——使用 md-padding 给 Markdown 自动加空格